# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Card(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, customer_id: int=None, customer_name: str=None, card_number: str=None, card_expiry: str=None, primary1: str=None):  # noqa: E501
        """Card - a model defined in Swagger

        :param id: The id of this Card.  # noqa: E501
        :type id: int
        :param customer_id: The customer_id of this Card.  # noqa: E501
        :type customer_id: int
        :param customer_name: The customer_name of this Card.  # noqa: E501
        :type customer_name: str
        :param card_number: The card_number of this Card.  # noqa: E501
        :type card_number: str
        :param card_expiry: The card_expiry of this Card.  # noqa: E501
        :type card_expiry: str
        :param primary1: The primary1 of this Card.  # noqa: E501
        :type primary1: str
        """
        self.swagger_types = {
            'id': int,
            'customer_id': int,
            'customer_name': str,
            'card_number': str,
            'card_expiry': str,
            'primary1': str
        }

        self.attribute_map = {
            'id': 'id',
            'customer_id': 'customer_id',
            'customer_name': 'customer_name',
            'card_number': 'card_number',
            'card_expiry': 'card_expiry',
            'primary1': 'primary1'
        }
        self._id = id
        self._customer_id = customer_id
        self._customer_name = customer_name
        self._card_number = card_number
        self._card_expiry = card_expiry
        self._primary1 = primary1

    @classmethod
    def from_dict(cls, dikt) -> 'Card':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Card of this Card.  # noqa: E501
        :rtype: Card
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Card.


        :return: The id of this Card.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Card.


        :param id: The id of this Card.
        :type id: int
        """

        self._id = id

    @property
    def customer_id(self) -> int:
        """Gets the customer_id of this Card.


        :return: The customer_id of this Card.
        :rtype: int
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: int):
        """Sets the customer_id of this Card.


        :param customer_id: The customer_id of this Card.
        :type customer_id: int
        """

        self._customer_id = customer_id

    @property
    def customer_name(self) -> str:
        """Gets the customer_name of this Card.


        :return: The customer_name of this Card.
        :rtype: str
        """
        return self._customer_name

    @customer_name.setter
    def customer_name(self, customer_name: str):
        """Sets the customer_name of this Card.


        :param customer_name: The customer_name of this Card.
        :type customer_name: str
        """

        self._customer_name = customer_name

    @property
    def card_number(self) -> str:
        """Gets the card_number of this Card.


        :return: The card_number of this Card.
        :rtype: str
        """
        return self._card_number

    @card_number.setter
    def card_number(self, card_number: str):
        """Sets the card_number of this Card.


        :param card_number: The card_number of this Card.
        :type card_number: str
        """

        self._card_number = card_number

    @property
    def card_expiry(self) -> str:
        """Gets the card_expiry of this Card.


        :return: The card_expiry of this Card.
        :rtype: str
        """
        return self._card_expiry

    @card_expiry.setter
    def card_expiry(self, card_expiry: str):
        """Sets the card_expiry of this Card.


        :param card_expiry: The card_expiry of this Card.
        :type card_expiry: str
        """

        self._card_expiry = card_expiry

    @property
    def primary1(self) -> str:
        """Gets the primary1 of this Card.


        :return: The primary1 of this Card.
        :rtype: str
        """
        return self._primary1

    @primary1.setter
    def primary1(self, primary1: str):
        """Sets the primary1 of this Card.


        :param primary1: The primary1 of this Card.
        :type primary1: str
        """

        self._primary1 = primary1
